### PR TITLE
fix start command for server

### PR DESCRIPTION
**Pull request by rdinicut**

### CODE REVIEW

**Comment by rdinicut** [comment]
@charleenfei for some reason I can not add you as a reviewer. Maybe it is because I am not part of team/project

**Comment by charleenfei** [comment]
is this necessary? server start seems to work fine as is on `npm run start`

**Comment by rdinicut** [comment]
It did not work for me when running npm start from the root folder and the nodemon was not loading the server project. It was launching just the front end and I was getting a can not proxy to localhost 3001 error

**Comment by rdinicut** [comment]
image

**Review by charleenfei — APPROVED** [review]

**Pull request merged**
