### PR TITLE
fix: implement class-transformer to exclude password

### PR DESCRIPTION
**Pull request by jpangelle**
### Description

This pull request adds the [class-transformer](https://github.com/typestack/class-transformer) library as recommended by the [nestjs](https://docs.nestjs.com/techniques/serialization) library in order to exclude specific properties from a class. `password` and `secret` will now be excluded from the network response when a user logins.

~~I did not abstract the exclusion into a sanitization helper since this is the first instance. If we use this functionality repeatedly in the future, it will be clearer as to how we can design a more generic helper.~~

I abstracted the sanitation logic into a `PublicUser` class since this is being used in several places within the users controller.

I tried to implement a unit test to test that the properties were properly excluded, but I found out it is not possible to test for this in unit tests, only in e2e tests. I joined the NestJS discord and found this comment from one of the contributors:

Screen Shot 2021-04-19 at 1 59 23 PM

### CODE REVIEW

**Review by philipstanislaus — COMMENTED** [review]
Awesome 👏  

Is the user class used everywhere now? Need to check again, but I remember there were more places where we returned the user

**Comment by jpangelle** [comment]
> Awesome 👏
> 
> Is the user class used everywhere now? Need to check again, but I remember there were more places where we returned the user

After another look, you are right. There were a few more places. Because of this, I created a `PublicUser` class that extends the `User` class but with the `password` and `secret` excluded and used this `PublicUser` class in the users controller. What do you think of this approach?

**Comment by jpangelle** [comment]
@philipstanislaus I rebased on top of the jwt changes. Can you re-review?

**Comment by philipstanislaus** [comment]
Thanks @jpangelle , I just changed a few minor things and applied the interceptor globally.

I also updated the tests, but the excluded fields are still present, so the tests currently fail. 

Would you have a look at that? Maybe we need to revert my global interceptor to methods, but that's a bit of a limitation.

Thanks!

**Pull request merged**
